config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :endroits

  root "users#index"

end

app/models/endroit.rb
class Endroit < ActiveRecord::Base
	geocoded_by :adresse
	after_validation :geocode
	belongs_to :user

	def windspeed
		ForecastIO.forecast(self.latitude, self.longitude).currently.windSpeed
	end



end
	

app/models/sport.rb
class Sport < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :endroits
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/endroits_controller.rb
class EndroitsController < ApplicationController
	
	def index
		@endroits = Endroit.all
	end

	def show
		@endroit = Endroit.find(params[:id])
		@windspeed = @endroit.windspeed
	end
	
	def new
	 	@endroits = Endroit.new
	end

	def create
		@endroits = Endroit.new(endroit_param)
      if @endroits.save
      	redirect_to endroits_path, method: :get, notice: "Votre endroits a été créé"
      else
      	render 'new'
      end
  end

	def destroy
		@endroit = Endroit.find(params[:id])
		@endroit.destroy

		redirect_to 'lien de la page', notice: "Votre Endroit a bien été supprimé"
	end

	private

		def endroit_param
			params.require(:endroit).permit(:nom, :adresse)
		end
end

app/controllers/sport_controller.rb
class SportController < ApplicationController
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
	def index
		@sports = Sport.all

		tab = []
		(0..@sports.length-1).each do |num|
			tab << num
		end

		@sports_rdm = []
		(0..10).each do |e|
			rdm = Random.new.rand(0..tab.length-1)
			@sports_rdm << @sports[tab[rdm]]
			tab.delete_at(rdm)
		end
	end

	def show
		@sport = Sport.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endroits_helper.rb
module EndroitsHelper
end

app/helpers/sport_helper.rb
module SportHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/endroits/index.html.erb
<% @endroits.each do |endroit| %>
	<%= endroit.nom %></br>
	<%= endroit.adresse %></br>
</br>
<% end %> 

app/views/endroits/new.html.erb
<%= form_for(@endroits) do |f| %>

	<%= f.text_field :nom, placeholder: "Entrez un nom" %>

	<%= f.text_field :adresse, placeholder: "Entrez une adresse" %>

	<%= f.submit "Enregistrer", class: "btn btn-info btn-md" %>

<% end %>

app/views/endroits/show.html.erb
<%= @endroit %>
<%= @windspeed %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackathon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"></button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">          
              <li><%= link_to "Sportivity", root_path, method: :get %> </li>   
              <li><%= link_to "Mon profil", root_path, method: :get %></li>
              <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
          </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>
<%= yield %>

</body>
</html>

app/views/sports/index.html.erb
<h1>Sports</h1>
<% @sports.each do |sport| %>
	
	<div class ='sport'>
		<h3><%= sport.name %></h3>
		<%= link_to image_tag(sport.image), sport_path(sport.id), method: :get %>
	</div>
<% end %>

app/views/sports/show.html.erb
<%= @sport.name %>
<%= image_tag @sport.image%>
<%= button_to "Add this sport", sports_path, method: :get %>

app/views/users/index.html.erb
<h1>Bonjour</h1>

<%= link_to 'new',  new_endroit_path, method: :get %>